config/routes.rb
NewTwist::Application.routes.draw do

  
  
  resources :tweets
  resources :comments

  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"

  get "users/show"
  get "users/index"
  get "comments/recent"

  root 'welcome#index'

  devise_for :users, :controllers => { :registrations => "registrations" }
  

 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :tweet
	belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :comments
  has_many :tweets
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_devise_params, if: :devise_controller?
  	def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :photo_url, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  include TweetsHelper
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
   #@tweet = comment.tweet
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @tweet_id = params[:tweet_id]
    @tweet = Tweet.find(@tweet_id)
    @user = @comment.user

  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    #@tweet = comment.tweet
    #set_num_comments(comment_params[:tweet_id])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:tweet_id, :user_id, :comment)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    #@user = @tweet.user
    #@comments = @tweet.comments
    #@num_comments = @tweet.comments.count
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @user = @tweet.user

    @num_comments = @tweet.comments.count
  end

  def update_all_tweets

    tweets = Tweet.all

    @response_html = ""

    tweets.each do |tweet|
      set_num_comments (tweet.id)

      @response_html += "Update tweet <b>#{tweet.id}<b><br><br> \n "

    end

  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @user = @tweet.user
    @comments = @tweet.comments
    @num_comments = @tweet.comments.count
    @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tweet }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :tweet, :num_comments)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	users= User.all
  end

  def about
  	users= User.all
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def set_num_comments(posted_tweet_id)
		num_comments = Comment.where("tweet_id = #{posted_tweet_id}").count
	tweet = Tweet.find(posted_tweet_id)
	tweet.num_comments = num_comments
	tweet.save
end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th>User</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.tweet_id %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @comment.tweet %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to image_tag("/assets/Lime-Twist.png", :width => 100, :height => 100, :border => 0, :alt => '', :title => ''), root_path, :class => "navbar-brand" %>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
        <%= link_to 'About', welcome_about_path, class: 'navbar-brand'%>
        <%= link_to 'Tweets', tweets_path, class: 'navbar-brand'%>
      </div>

    <div class="collapse navbar-collapse">

      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>

      
  
  <% if user_signed_in? %>
      <div class="navbar pull-right">
      <img  width= 100 src=  <%= current_user.photo_url %> alt="profile pic" class="img-circle">
      <center>Hi, <%=current_user.first_name %>!</center>
      </div>


      <p class="navbar-text pull-right">
      Logged in as <strong> <%= current_user.email %> </strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      
     
   
  <% else %>
  <p class="navbar-text float-right">
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "New Twist" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "New Twist" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
  <!--<% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
    <% end %>
  -->
       <%= yield %>
    </main>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
-->
  <div class="field">
    <%= f.label :tweet %><br>
    <%= f.text_area :tweet %>
  </div>
<!--
  <div class="field">
    <%= f.label :num_comments %><br>
    <%= f.number_field :num_comments %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<center>
<h1>Tweets</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Tweet</th>
      <th>Num comments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user_id %></td>
        <td><%= tweet.tweet %></td>
        <td><%= tweet.num_comments %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit ', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
</p>


<p>
  <%= @tweet.tweet %>
</p>


<p>
  <strong>Comments:</strong>
  <%= @tweet.comments.all %>
</p>

<p>
  <%= link_to "Add a comment", new_comment_path(:tweet_id=>@tweet.id) %>
</p>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/welcome/about.html.erb
<center>
<br>
<br>
<img src= "/assets/Lime-Twist.png" height= 100 width= auto>
<h1>About Twist</h1>
<p> Twist is a project that I created which is similar to Twitter. I used Ruby with Ruby on Rails as a framework and Postgresql for database management. I also used the Devise gem for authentication and Bootsrap for styling. It has been a very challenging project, and I've broken it a gazillion times already, but it get easier to rebuild each time and hence has been a great learning experience!
***Please note that it is still a work in progress!***
</center>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Twist!</h1>
<img src= "/assets/Lime-Twist.png">